# Generated by Django 2.2.16 on 2020-09-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'GEN_REMINDER'), (2, 'LM_REMINDER'), (3, 'WISHDAY')], default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
