# Generated by Django 2.2.16 on 2020-09-07 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailedlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 23, 41, 5, 481061, tzinfo=utc)),
        ),
    ]
