# Generated by Django 2.2.16 on 2020-09-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.IntegerField(choices=[(1, 'AQUIRED'), (0, 'RELEASED')], default=1)),
            ],
        ),
    ]
