# Generated by Django 2.2.16 on 2020-10-05 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='mailedlist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
