# Generated by Django 2.2.16 on 2020-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='bday',
            field=models.DateField(verbose_name='birthday'),
        ),
    ]
