# Generated by Django 2.2.16 on 2020-09-04 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_birthday_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='bdate',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 1), verbose_name='birthdate'),
        ),
    ]
