# Generated by Django 2.2.16 on 2020-10-05 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_birthday_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='bdate',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), verbose_name='birthdate'),
        ),
    ]
